server:
  port: 8080

spring:
  datasource:
    name: pos
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 相关配置
    druid:
      filter: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://132.232.140.51:3306/poss?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #liquibase
  liquibase:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fanghong.pos.Model

pagehelper:
  #dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# slf4j日志配置
logging:
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别
    com.fanghong.pos: trace
  file: springboot.log

log:
  path: /home/fanghong/logs
  level: debug